name: 'Set version number'
description: 'set the version number of solutions in the source folder'
inputs:
   source_folder:
    required: true
    type: string
    description: "Source folder"
   version_number: 
    required: true
    type: string
    description: "Version number of the solutions, e.g. 1.0.0.0"
outputs:
  files-changed:
    description: "Files changed"
    value: ${{ steps.set-version.outputs.files-changed }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set-version
      run: |
        count=0
        # Find all Solution.xml files in the solution directory and its subdirectories
        find ${{ inputs.source_folder }} -type f -name "Solution.xml" | while read -r file; do
        # Replace the content of the <Version> tag with version number provided in the input
             sed -i 's|<Version>.*</Version>|<Version>${{ inputs.version_number }}</Version>|g' "$file"
             # If sed command was successful, increment the counter
             if [ $? -eq 0 ]; then
              ((count++))
             fi
        done
        # Print the number of files changed
        echo "Number of files changed: $count"
        echo "files-changed=$(echo $count)" >> $GITHUB_OUTPUT
   
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}


