name: 'Set version number'
description: 'set the version number of solutions in the source folder'
inputs:
   source_folder:
    required: true
    type: string
    description: "Source folder"
   version_number: 
    required: true
    type: string
    description: "Version number of the solutions, e.g. 1.0.0.0"
outputs:
  files-changed:
    description: "Files changed"
    value: ${{ steps.set-version.outputs.files-changed }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set-version
      run: |
       echo "hello"
       echo "dsfsdf"
   
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}


