name: CD-to-Prod

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  solution_name: mpa_Kudos
  solution_source_folder: src
  solution_outbound_folder: out/solutions
  solution_release_folder: out/release
jobs:
  convert-to-managed:
   runs-on: windows-latest
   steps:
   - uses: actions/checkout@v2
     with:
       lfs: true
   - name: Pack managed solution
     uses: microsoft/powerplatform-actions/pack-solution@v0
     with:
       solution-folder: ${{ env.solution_source_folder}}/${{ env.solution_name }}
       solution-file: ${{ env.solution_outbound_folder}}/${{ env.solution_name }}_managed.zip
       solution-type: Managed
   - name: Pack unmanaged solution
     uses: microsoft/powerplatform-actions/pack-solution@v0
     with:
       solution-folder: ${{ env.solution_source_folder}}/${{ env.solution_name }}
       solution-file: ${{ env.solution_outbound_folder}}/${{ env.solution_name }}_unmanaged.zip
       solution-type: Unmanaged
   - name: Upload the unmanaged solution to GH artifact store
     uses: actions/upload-artifact@v2
     with:
       name: unmanagedSolutions
       path: ${{ env.solution_outbound_folder}}/${{ env.solution_name }}_unmanaged.zip             
   - name: Upload the managed solution to GH artifact store
     uses: actions/upload-artifact@v2
     with:
       name: managedSolutions
       path: ${{ env.solution_outbound_folder}}/${{ env.solution_name }}_managed.zip 

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{ env.solution_release_folder}}
    - run: |
        cd ${{ env.solution_release_folder}}
        dir
    - run: |
        newDataverseId="cc54b39cf98e41e0969dfdd7b90e2e6a"
        newO365Id="4b143239cbbc4443a43466481bc39586"
        newOutlookId="c3a653db1d234550af69f51c22389c5d"
        cat deploymentSettings.json | jq --arg dataverseId "$newDataverseId" --arg o365Id "$newO365Id" --arg outlookId "$newOutlookId" '.ConnectionReferences[] |= 
         if .ConnectionId == "[Dataverse]" then .ConnectionId = $dataverseId
         elif .ConnectionId == "[O365]" then .ConnectionId = $o365Id
         elif .ConnectionId == "[Outlook]" then .ConnectionId = $outlookId
        else . end' > temp.json && mv temp.json deploymentSettings.json
  
    - name: Import solution to test env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: "https://orgae9e123c.crm.dynamics.com"
        app-id: ${{secrets.PPAPPID}}
        client-secret: ${{ secrets.PPAPPSECRET }}
        tenant-id: ${{secrets.PPTENANTID}}
        solution-file: ${{ env.solution_release_folder}}/${{ env.solution_name }}_managed.zip
        deployment-settings-file: ${{ env.solution_source_folder}}/deploymentSettings.json
        run-asynchronously: true
