name: GitHub Release
on:
  workflow_dispatch: 
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 1.0.0.0
      release_notes:
        description: 'Release notes'
        required: true
        default: 'Initial release'
      release_title:
        description: 'Release title'
        required: true
        default: 'Initial release'
       
jobs:
  set-version:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: Set version number
      uses: ./.github/actions/set-version-number-action
      id: set-version
      with:
        source_folder: src
        version_number: ${{ inputs.release_version }}
    - run: echo files changed "$CHANGE"
      shell: bash
      env:
         CHANGE: ${{ steps.set-version.outputs.random-number }}

    
  release:
   needs: [ set-version ]
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Authenticate gh cli
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    - name: Create a release
      shell: bash
      run: | 
       #gh release create ${{inputs.release_version}} -t ${{inputs.release_version}} -n ${{inputs.release_notes}} \
       #  --generate-notes 
       gh release create ${{inputs.release_version}} --generate-notes
       echo "Release created successfully"

  
