name: GitHub Release
on:
  workflow_dispatch: 
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 1.0.0.0
      release_notes:
        description: 'Release notes'
        required: true
        default: 'Initial release'
      release_title:
        description: 'Release title'
        required: true
        default: 'Initial release'
       
jobs:
  set-version-and-build:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v4
    # composite action to set the version number
    - name: Set version number
      uses: ./.github/actions/set-version-number-action
      id: set-version
      with:
        source_folder: src
        version_number: ${{ inputs.release_version }}
    - run: echo files changed "$CHANGE"
      shell: bash
      env:
         CHANGE: ${{ steps.set-version.outputs.files-changed }}
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build with MSBuild
      run: msbuild .\src\solutions.proj /p:Configuration=Release
      shell: cmd
    - name: Upload build artifacts - Kudos
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts-Kudos
        path: .\src\mpa_Kudos\bin\Release\*_managed.zip
    - name: Upload build artifacts - Employee Experience
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts-EE
        path: .\src\mpa_EmployeeExperienceBase\bin\Release\*_managed.zip
        type: zip
    - name: Build with MSBuild
      run: |
        cd src
        cd DeploymentPackage
        dotnet publish -c Release
      shell: cmd
    - name: Upload build artifacts - Deployment Package
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts-DeploymentPackage
        path: .\src\DeploymentPackage\bin\Release\*.zip
        type: zip
    
  release:
   needs: [ set-version-and-build ]
   runs-on: ubuntu-latest
   permissions:
    contents: write
   steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Authenticate gh cli
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    - name: Create a release
      shell: bash
      run: | 
       #gh release create ${{inputs.release_version}} -t ${{inputs.release_version}} -n ${{inputs.release_notes}} \
       #  --generate-notes 
       gh release create ${{inputs.release_version}} --generate-notes
       echo "Release created successfully"

  
