name: Set version number (reusable)
on:
    workflow_call:
      inputs:
        source_folder:
          required: true
          type: string
          description: "Source folder"
        version_number: 
         required: true
         type: string
         description: "0.0.0.0"
jobs:
    pack-solution:
      runs-on: ubuntu-latest
      steps:
        - run: |
            set -e
            # Set the path to the directory containing the solution
            solution_dir="${{ inputs.source_folder }}"
            # Find all Solution.xml files in the solution directory and its subdirectories
            find "$solution_dir" -type f -name "Solution.xml" | while read -r file; do
            # Replace the content of the <Version> tag with version number provided in the input
            sed -i 's|<Version>.*</Version>|<Version>${{ inputs.version_number }}</Version>|g' "$file"
            done
    